# Python, päev 1

Täna õpime Pythoni baasasju kasutama.

## *Hello, World!*

In [35]:
print("Hello, World! (string ehk sõne)")

Hello, World! (string ehk sõne)

## Andmetüübid

In [36]:
PI = 3.14 # float ehk floating point ehk ujukomaarv
aasta = 2026 # int ehk integer ehk täisarv
sun_rises_from_east = True # bool ehk tõeväärtus true/false

In [37]:
years = [2020, 2021, 2022, 2023, 2024, 2025, 2026] # list ehk järjend, järjestatud ja muudetav kogum elemente
person = {
    "name": "Alice", 
    "age": 30, 
    "city": "New York"
} # dict ehk sõnastik, võtme-väärtuse paaride kogum, järjestamata ja muudetav

fruits = {"apple", "banana", "cherry"} # set ehk hulk, järjestamata ja muutumatu kogum elemente
tuple_example = (1, 2, 3) # tuple ehk paarennik ehk paar, järjestatud ja muutumatu kogum elemente

## Funktsioonid

In [38]:
def greet():
    print("Hello from the greet function!")
    print("And some more things going on here...") 
    # function ehk funktsioon, koodiplokk, mida saab mitu korda kasutada

print("not in function")

not in function

In [39]:
greet()

Hello from the greet function!
And some more things going on here...

In [40]:
def greet(name: str, time_of_day: str="day"):
    print(f"Good {time_of_day}, {name}!")

In [41]:
greet("Mati")
greet("Alice", "evening")
greet(name="Bob", time_of_day="morning")
greet(time_of_day="morning", name="Charlie")

Good day, Mati!
Good evening, Alice!
Good morning, Bob!
Good morning, Charlie!

In [42]:
number = 42
f"Number is {number}" # f-string ehk formatted string, võimaldab lisada stringi muutujate väärtusi

'Number is 42'

In [43]:
def add(a: int, b: int) -> int:
    """Liidab kaks arvu kokku ja tagastab tulemuse."""
    return a + b

In [44]:
result = add(1, 5)
print(result)

6

## if/else

In [45]:
def make_sense_of_this_year(year: int):
    if year < 0:
        print("B.C")
        # year = -90 => halb praktika lisada funktsioon võrdluste sisse
        if year < -10000:
            print("Stone age...")
    elif year == 0:
        print("Happy birthday, Jesus!")
    elif year == 1978:
        print("Happy birthday, Mati!")
    else:
        print("A.D")

make_sense_of_this_year(-90)
make_sense_of_this_year(year=-90)

B.C
B.C

In [46]:
def format_year(year: int) -> str:
    if year < 0:
        return (f"{abs(year)} B.C")
    else:
        return (f"{year} A.D")

print(format_year(-90))
print(format_year(year=2025))

90 B.C
2025 A.D

In [1]:
import datetime
datetime.date.today()

datetime.date(2026, 4, 14)

## For loop

In [47]:
years = [2021, 2022, 2023, 2024, 2025]

for year in years:
    print(f"Happy startt of {year}")

Happy startt of 2021
Happy startt of 2022
Happy startt of 2023
Happy startt of 2024
Happy startt of 2025

In [48]:
years = [2021, 2022, 2023, 2024, 2025]

for year in years [:4]:
    print(f"Happy startt of {year}")

Happy startt of 2021
Happy startt of 2022
Happy startt of 2023
Happy startt of 2024

In [49]:
print(years[:3]) # esimesed kolm listist
years[3:] # kolmandast alates listist

[2021, 2022, 2023]

[2024, 2025]

In [2]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

## Pandas

In [50]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from scikit-learn) (3.6.0)

In [51]:
!pip install duckdb

Requirement already satisfied: duckdb in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (1.5.1)

In [52]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [53]:
import pandas as pd
import duckdb

In [54]:
data = pd.DataFrame({
    "name": ["A", "B", "C"],
    "age": [30, 25, 35],
    "city": ["York", "Los", "Chi"]
})
data

  name  age  city
0    A   30  York
1    B   25   Los
2    C   35   Chi

In [55]:
data.to_csv("not_very_sensible_data.csv", index=False)

In [56]:
people = pd.read_csv("not_very_sensible_data.csv")
people

  name  age  city
0    A   30  York
1    B   25   Los
2    C   35   Chi

In [ ]:
people[["name", "age"]] # välimine paar ütleb, anna mulle tulbad ja sisemine paar näitab, et tegemist on listiga

  name  age
0    A   30
1    B   25
2    C   35

In [4]:
from sklearn.datasets import load_iris
import pandas as pd

iris_data = load_iris()
iris = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris['target'] = iris_data.target
iris['species'] = iris['target'].map(dict(enumerate(iris_data.target_names)))
iris.pop('target')
iris = iris.rename(columns={
    "sepal length (cm)": "sepal_lenght",
    "sepal width (cm)": "sepal_width",
    "petal length (cm)": "petal_lenght",
    "petal width (cm)": "petal_width"
})
iris

     sepal_lenght  sepal_width  petal_lenght  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
iris.to_csv("iris.csv", index=False)

In [59]:
duckdb.sql("""
    SELECT 'Hello, World!'
""")

┌─────────────────┐
│ 'Hello, World!' │
│     varchar     │
├─────────────────┤
│ Hello, World!   │
└─────────────────┘

In [60]:
duckdb.sql("""
    SELECT *
    FROM iris
    """).df()

     sepal_lenght  sepal_width  petal_lenght  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [61]:
duckdb.sql("""
    SELECT 
        species,
        avg(petal_lenght) as avg_petal_lenght
    FROM iris
    GROUP BY species
    ORDER BY avg_petal_lenght DESC
    """).df()

      species  avg_petal_lenght
0   virginica             5.552
1  versicolor             4.260
2      setosa             1.462

In [62]:
def funktsioon_enne_voi_parast_kristust(aasta: int) -> str:
    if aasta < 0:
        return f"{abs(aasta)} B.C"
    else:
        return f"{aasta} A.D"
    
funktsioon_enne_voi_parast_kristust(12)

'12 A.D'

In [63]:
inimesed = ['Kati', 'Mati', 'Silver', 'Hannes']

jarjekorranumber = 0

for nimi in inimesed:
    jarjekorranumber += 1
    if len(nimi) > 4:
        print(f"Inimene nr. {jarjekorranumber} kannab pikka nime {nimi}")
    else:
        print(f"Inimene nr. {jarjekorranumber} kannab lühikest nime {nimi}")

Inimene nr. 1 kannab lühikest nime Kati
Inimene nr. 2 kannab lühikest nime Mati
Inimene nr. 3 kannab pikka nime Silver
Inimene nr. 4 kannab pikka nime Hannes

In [64]:
inimesed = ['Kati', 'Mati', 'Silver', 'Hannes']
numbrid = ['esimene', 'teine', 'kolmas', 'neljas']

jarjekorranumber = 0 # teeme muutuja, et hiljem järjekorranumbreid muuta
jarjekord = numbrid[jarjekorranumber].capitalize() # teeme muutuja, et valem loetavam oleks

for nimi in inimesed:
    jarjekord = numbrid[jarjekorranumber].capitalize()
    if len(nimi) > 4:
        print(f"{jarjekord} inimene kannab pikka nime {nimi}")
    else:
        print(f"{jarjekord} inimene kannab lühikest nime {nimi}")
    jarjekorranumber += 1

Esimene inimene kannab lühikest nime Kati
Teine inimene kannab lühikest nime Mati
Kolmas inimene kannab pikka nime Silver
Neljas inimene kannab pikka nime Hannes

- vaja leida kogu hind
- kui hind on üle 100, siis 20% alla
- kui hind on üle 50, siis 10% alla

sammud:
- leida allahindlusega hind igale hinnale
- kokku liita

In [1]:
hinnad = [120, 45, 89, 200, 33, 75, 150, 10, 99, 101]

def get_discount(price: int) -> float: #funktsioon funktsiooni nimi(argumendi nimi: argumendi tüüp) -> tulemuse tüüp
    """
    seefunktsioon arvutab allahindlust
    """
    if price > 100:
        return price * 0.8
    if price > 50:
        return price * 0.9
    return price

def get_price(prices: list[int]) -> float: #loon funktsiooni allahinnatud ja mitte hindade summeerimiseks
    tulemus = 0
    for hind in prices:
        allahindlusega_hind = get_discount(hind)
        tulemus = tulemus + allahindlusega_hind
    return tulemus

def get_price_short(prices: list[int]) -> float:
    return sum([get_discount(hind) for hind in prices])

get_price_short(hinnad)

781.5

In [ ]:
print(round(sum([1,2,3]))) # näide mitmest funktsioonist, töötab seest välja poole

6